version: "2.2"
services:
  mysql-service:
    image: mysql:5.7
    container_name: mysql
    networks:
      - spring-boot-mysql-network
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=bookstore
  api-service:
    container_name: api-bookstore
    image: viniciusrs/bookstore-jar:latest
    #    build:
    #      context: ./
    #      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=production
    ports:
      - "4300:8080"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service
    restart: on-failure
networks:
  spring-boot-mysql-network:
    driver: bridge