version: "2.2"
services:
  mysql-service:
    image: mysql:5.7
    container_name: mysql
    networks:
      - spring-boot-mysql-network
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=bookstore
  api-service:
    container_name: api-bookstore
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service
networks:
  spring-boot-mysql-network:
    driver: bridge