spring:
  profiles: develop
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 1234
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: MySQL57Dialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: bookstore
    drop-first: false
---
spring:
  profiles: prod